name: TO run only if commit message has Deploy in it

on:
  push:

jobs:
    conditional-job:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy
              run: echo "Commit message has Deploy , Deploying to main..."
              if: contains(github.event.head_commit.message,'Deploy') 
            - name: Skip Deployment
              run: echo "Skipping Deployment..."
              if: contains(github.event.head_commit.message,'Deploy') == false
