name: TO run only if commit message has Deploy in it

on:
  push:

jobs:
    conditional-job:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy
              run: echo "Commit message has Deploy , Deploying to main..."
              if: github.ref == 'refs/heads/test' && contains(github.event.head_commit.message,'Deploy') 
            - name: If job success
              run: echo "Job Succeeded!"
              if: success()
            - name: If job failed
              run: echo "Job Failed!"
              if: failure()
